---
version: "3.7"
services:
  front-envoy:
    build: .
    networks:
      - envoymesh
    volumes:
      - ./envoy.yaml:/etc/front-envoy.yaml
    expose:
      - "8080"
      - "8443"
      - "8001"
    ports:
      - "8080:8080"
      - "8443:8443"
      - "8001:8001"

  auth:
    image: zwiter/auth:1.0
    networks:
      envoymesh:
        aliases:
          - auth
    environment:
      GODEBUG: x509ignoreCN=0
      SERVICE_NAME: auth
    volumes:
      - ./auth/config:/config
      - ./auth/bin:/zwitter-bin
    expose:
      - "8000"
      - "9999"

  posts:
    image: zwiter/posts:1.0
    networks:
      envoymesh:
        aliases:
          - posts
    environment:
      GODEBUG: x509ignoreCN=0
      SERVICE_NAME: posts
    volumes:
      - ./posts/config:/config
      - ./posts/bin:/zwitter-bin
    expose:
      - "8000"
      - "7777"

  users:
    image: zwiter/users:1.0
    networks:
      envoymesh:
        aliases:
          - users
    environment:
      GODEBUG: x509ignoreCN=0
      SERVICE_NAME: users
    volumes:
      - ./users/config:/config
      - ./users/bin:/zwitter-bin
    expose:
      - "8000"
      - "8888"

networks:
  envoymesh: {}
