version: "3.7"
services:

  posts:
    image: zwiter-posts
    ports:
      - "7777:7777"
      - "7778:7778"
    network_mode: host
    environment:
      GODEBUG: x509ignoreCN=0
    volumes:
      - ./posts/config:/config
      - ./posts/bin:/zwitter-bin

  auth:
    image: zwiter-auth
    ports:
      - "9990:9990"
      - "9999:9999"
    network_mode: host
    environment:
      GODEBUG: x509ignoreCN=0
    volumes:
      - ./auth/config:/config
      - ./auth/bin:/zwitter-bin

  users:
    image: zwiter-users 
    ports:
      - "8889:8889"
      - "8888:8888"
    network_mode: host
    environment:
      GODEBUG: x509ignoreCN=0
    volumes:
      - ./users/config:/config
      - ./users/bin:/zwitter-bin

networks:
  ist:
