Server:
  Name: Auth
  GrpcAddr: localhost:9999
  RestAddr: localhost:9990
  CertFile: ./cert/server.crt
  KeyFile: ./cert/server.key
  ServerName: grpcserver
  Nodes:
    - Name: Posts
      Host: posts
      Port: 7777
    - Name: Users
      Host: users
      Port: 8888
