Server:
  Name: Auth
  GrpcAddr: localhost:7777
  RestAddr: localhost:7778
  CertFile: ./cert/server.crt
  KeyFile: ./cert/server.key
  ServerName: grpcserver
  Nodes:
    - Name: Auth
      Host: auth
      Port: 9999
    - Name: Users
      Host: users
      Port: 8888
