name: Build and test

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        go get -u golang.org/x/lint/golint
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi
    - name: Build-Auth
      run: |
        cd auth
        make
        cd ..

    - name: Build-Posts
      run: |
        cd posts
        make
        cd ..
        
    - name: Build-Users
      run: |
        cd users
        make
        ..

    - name: Test
      run: go test -v ./...
